import { Project, Profile, ProjectMember, Task, GameplayVideo, FileRecord } from '@/types/database';

export const MOCK_CURRENT_USER: Profile = {
  id: 'user-shin',
  display_name: 'Katsuragi Shin',
  avatar_url: 'https://api.dicebear.com/7.x/bottts/svg?seed=Shin',
  created_at: '2026-09-01T08:00:00Z',
  updated_at: '2026-10-08T08:00:00Z',
};

export const MOCK_MEMBERS: (ProjectMember & { profile: Profile })[] = [
  {
    id: 'pm-1',
    project_id: 'proj-1',
    user_id: 'user-shin',
    role: 'OWNER',
    created_at: '2026-09-01T08:00:00Z',
    profile: MOCK_CURRENT_USER,
  },
  {
    id: 'pm-2',
    project_id: 'proj-1',
    user_id: 'user-ren',
    role: 'ADMIN',
    created_at: '2026-09-01T08:00:00Z',
    profile: {
      id: 'user-ren',
      display_name: 'Ren (Lead Artist)',
      avatar_url: 'https://api.dicebear.com/7.x/bottts/svg?seed=Ren',
      created_at: '2026-09-01T08:00:00Z',
      updated_at: '2026-10-08T08:00:00Z',
    },
  },
  {
    id: 'pm-3',
    project_id: 'proj-1',
    user_id: 'user-mai',
    role: 'MEMBER',
    created_at: '2026-09-01T08:00:00Z',
    profile: {
      id: 'user-mai',
      display_name: 'Mai (Gameplay Dev)',
      avatar_url: 'https://api.dicebear.com/7.x/bottts/svg?seed=Mai',
      created_at: '2026-09-01T08:00:00Z',
      updated_at: '2026-10-08T08:00:00Z',
    },
  },
  {
    id: 'pm-4',
    project_id: 'proj-1',
    user_id: 'user-tuan',
    role: 'VIEWER',
    created_at: '2026-09-01T08:00:00Z',
    profile: {
      id: 'user-tuan',
      display_name: 'Tuan (Publisher QA)',
      avatar_url: 'https://api.dicebear.com/7.x/bottts/svg?seed=Tuan',
      created_at: '2026-09-01T08:00:00Z',
      updated_at: '2026-10-08T08:00:00Z',
    },
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Pixel Knight: Rebirth',
    description: 'Dự án game nhập vai đi cảnh 2D pixel art với cơ chế combat tốc độ cao.',
    status: 'active',
    created_by: 'user-shin',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-10-08T08:00:00Z',
  },
  {
    id: 'proj-2',
    name: 'Project Tiny Colony',
    description: 'Game quản lý nông trại và xây dựng căn cứ phong cách thư giãn.',
    status: 'active',
    created_by: 'user-shin',
    created_at: '2026-08-01T08:00:00Z',
    updated_at: '2026-10-08T08:00:00Z',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    project_id: 'proj-1',
    title: 'Tối ưu hóa hệ thống particle và VFX khi Boss tung skill nộ',
    description: 'Hiện tại trên các máy cấu hình thấp FPS bị drop từ 60 xuống 35 khi boss thi triển chiêu nộ diện rộng.',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    assignee_id: 'user-shin',
    creator_id: 'user-ren',
    progress: 60,
    deadline: '2026-10-15T00:00:00Z',
    created_at: '2026-10-01T00:00:00Z',
    updated_at: '2026-10-08T00:00:00Z',
    assignee: MOCK_CURRENT_USER,
    checklist: [
      { id: 'c-1', task_id: 'task-1', label: 'Profiling GPU bằng RenderDoc', done: true, position: 0, created_at: '' },
      { id: 'c-2', task_id: 'task-1', label: 'Giảm số lượng emitter hạt từ 1200 xuống 400', done: true, position: 1, created_at: '' },
      { id: 'c-3', task_id: 'task-1', label: 'Batching draw calls cho spell texture atlas', done: false, position: 2, created_at: '' },
      { id: 'c-4', task_id: 'task-1', label: 'Test trên điện thoại Android tầm trung', done: false, position: 3, created_at: '' },
    ],
  },
  {
    id: 'task-2',
    project_id: 'proj-1',
    title: 'Vẽ spritesheet animation đòn combo 3 cho nhân vật chính',
    description: 'Cần 8 frame độ phân giải 64x64 pixel phong cách 16-bit.',
    status: 'TODO',
    priority: 'HIGH',
    assignee_id: 'user-ren',
    creator_id: 'user-shin',
    progress: 25,
    deadline: '2026-10-20T00:00:00Z',
    created_at: '2026-10-02T00:00:00Z',
    updated_at: '2026-10-08T00:00:00Z',
    assignee: MOCK_MEMBERS[1].profile,
    checklist: [
      { id: 'c-5', task_id: 'task-2', label: 'Phác thảo keyframe 1 & 4', done: true, position: 0, created_at: '' },
      { id: 'c-6', task_id: 'task-2', label: 'Vẽ motion blur & slash effect', done: false, position: 1, created_at: '' },
      { id: 'c-7', task_id: 'task-2', label: 'Xuất file Aseprite và PNG atlas', done: false, position: 2, created_at: '' },
    ],
  },
  {
    id: 'task-3',
    project_id: 'proj-1',
    title: 'Sửa lỗi va chạm (Collision bug) khiến người chơi rơi khỏi map ở hầm ngục 2',
    description: 'Khi dash liên tục vào góc tường mép trái, hitbox bị xuyên thấu.',
    status: 'TODO',
    priority: 'CRITICAL',
    assignee_id: 'user-shin',
    creator_id: 'user-mai',
    progress: 0,
    deadline: '2026-10-05T00:00:00Z', // Quá hạn (trước ngày 08/10/2026)
    created_at: '2026-10-01T00:00:00Z',
    updated_at: '2026-10-08T00:00:00Z',
    assignee: MOCK_CURRENT_USER,
    checklist: [
      { id: 'c-8', task_id: 'task-3', label: 'Tái hiện bug trong debug scene', done: false, position: 0, created_at: '' },
      { id: 'c-9', task_id: 'task-3', label: 'Bật continuous dynamic collision detection', done: false, position: 1, created_at: '' },
    ],
  },
  {
    id: 'task-4',
    project_id: 'proj-1',
    title: 'Tích hợp nhạc nền khu vực rừng ma ám (Spooky Forest BGM)',
    description: 'Loop track 2:45 chuẩn định dạng OGG Vorbis.',
    status: 'REVIEW',
    priority: 'NORMAL',
    assignee_id: 'user-mai',
    creator_id: 'user-shin',
    progress: 90,
    deadline: '2026-10-12T00:00:00Z',
    created_at: '2026-10-02T00:00:00Z',
    updated_at: '2026-10-08T00:00:00Z',
    assignee: MOCK_MEMBERS[2].profile,
    checklist: [
      { id: 'c-10', task_id: 'task-4', label: 'Chỉnh seamless audio loop point', done: true, position: 0, created_at: '' },
      { id: 'c-11', task_id: 'task-4', label: 'Cân bằng âm lượng (Audio mixing) với SFX', done: true, position: 1, created_at: '' },
    ],
  },
  {
    id: 'task-5',
    project_id: 'proj-1',
    title: 'Thiết kế hệ thống lưu dữ liệu Save/Load game cục bộ (Save Slot)',
    description: 'Hỗ trợ 3 save slots lưu trữ trạng thái level, inventory và equipment.',
    status: 'DONE',
    priority: 'HIGH',
    assignee_id: 'user-shin',
    creator_id: 'user-shin',
    progress: 100,
    deadline: '2026-10-02T00:00:00Z',
    created_at: '2026-09-25T00:00:00Z',
    updated_at: '2026-10-08T00:00:00Z',
    assignee: MOCK_CURRENT_USER,
    checklist: [
      { id: 'c-12', task_id: 'task-5', label: 'Mã hóa JSON save file (AES-128)', done: true, position: 0, created_at: '' },
      { id: 'c-13', task_id: 'task-5', label: 'Giao diện chọn slot lưu game', done: true, position: 1, created_at: '' },
      { id: 'c-14', task_id: 'task-5', label: 'Auto-save tại các điểm checkpoint', done: true, position: 2, created_at: '' },
    ],
  },
];

export const MOCK_VIDEOS: GameplayVideo[] = [
  {
    id: 'vid-1',
    project_id: 'proj-1',
    version: 'v0.4.2',
    title: 'Gameplay Demo: Boss Fight Hắc Long Ma Vương (60FPS)',
    description: 'Test cơ chế né đòn, parry và tương tác môi trường map dung nham.',
    file_key: 'projects/proj-1/video/boss_fight_test.mp4',
    thumbnail_key: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
    duration: 142,
    size: 284500000,
    uploaded_by: 'user-shin',
    created_at: '2026-10-07T12:00:00Z',
    uploader: MOCK_CURRENT_USER,
  },
  {
    id: 'vid-2',
    project_id: 'proj-1',
    version: 'v0.4.0',
    title: 'Trình diễn hệ thống combo kiếm thuật & phép thuật kết hợp',
    description: 'Đánh giá cảm giác lực chém (hitstop) và độ mượt khi đổi vũ khí.',
    file_key: 'projects/proj-1/video/combo_showcase.mp4',
    thumbnail_key: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    duration: 98,
    size: 198000000,
    uploaded_by: 'user-mai',
    created_at: '2026-10-04T12:00:00Z',
    uploader: MOCK_MEMBERS[2].profile,
  },
];

export const MOCK_FILES: FileRecord[] = [
  {
    id: 'file-1',
    project_id: 'proj-1',
    folder: 'builds',
    name: 'PixelKnight_v0.4.2_Windows_x64.zip',
    file_key: 'projects/proj-1/build/build_v0.4.2.zip',
    size: 1450000000,
    mime: 'application/zip',
    uploaded_by: 'user-shin',
    linked_task_id: 'task-1',
    created_at: '2026-10-07T14:00:00Z',
    uploader: MOCK_CURRENT_USER,
  },
  {
    id: 'file-2',
    project_id: 'proj-1',
    folder: 'assets',
    name: 'Boss_DarkDragon_Spritesheet_Full.ase',
    file_key: 'projects/proj-1/file/boss_dark_dragon.ase',
    size: 48500000,
    mime: 'application/octet-stream',
    uploaded_by: 'user-ren',
    linked_task_id: 'task-2',
    created_at: '2026-10-06T10:00:00Z',
    uploader: MOCK_MEMBERS[1].profile,
  },
  {
    id: 'file-3',
    project_id: 'proj-1',
    folder: 'audio',
    name: 'Spooky_Forest_OST_Master_96khz.wav',
    file_key: 'projects/proj-1/file/forest_theme.wav',
    size: 89000000,
    mime: 'audio/wav',
    uploaded_by: 'user-mai',
    linked_task_id: 'task-4',
    created_at: '2026-10-05T09:00:00Z',
    uploader: MOCK_MEMBERS[2].profile,
  },
];
